version: "3.8"

services: 

    client:
      build:
        context: ./client
        dockerfile: Dockerfile
      ports:
        - 3000:3000
     
    # Proxies request to internal services
    reverse-proxy:
        image: nginx:latest
        ports:
          - 80:80
        volumes:
          - ./client/build:/srv/www/static
          - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - users
            - tasks
            - client
    
    users:
        build: 
          context: ./users-api
          dockerfile: Dockerfile.prod
        ports:
          - 5001:5001
        volumes:
          - ./users-api:/src
          - /src/node_modules
        restart: on-failure

    tasks:
        build:
          context: ./tasks-api
          dockerfile: Dockerfile.prod
        ports:
          - 5000:5000
        volumes:
          - ./tasks-api:/src
          - ./src/node_modules
        restart: on-failure